WSP/rdfedit/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('WSP.rdfedit.views',
    url(r'^index/$', 'index', name='index'),
    url(r'^delete/$', 'delete', name='delete'),
    url(r'^(?P<doc_id>\d+)/spo/$', 'spo', name='spo'),
    url(r'^(?P<rdfxml_id>\d+)/rdf/$', 'rdf', name='rdf'),
    url(r'^new/$', 'newgraph', name='newgraph')
)

WSP/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from dajaxice.core import dajaxice_autodiscover, dajaxice_config
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

dajaxice_autodiscover()

urlpatterns = patterns('',
    (r'^rdfedit/', include('WSP.rdfedit.urls')),
    (r'^$', RedirectView.as_view(url='/rdfedit/index/')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

WSP/rdfedit/models.py
from django.db import models

#from WSP.rdfedit.filetypevalidator import ContentTypeRestrictedFileField

class Document(models.Model):
    docfile = models.FileField(
        upload_to='documents/%Y',
	)

    def __unicode__(self):
        return str(self.docfile)
 
class RDF_XML(models.Model):
    rdfxml_string = models.TextField()

WSP/rdfedit/forms.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label = 'Select a RDF file to upload end edit',
        #help_text = 'Accepted Formats: XML/RDF, RDF, N3 (not yet implemented)',
    )

class EndpointForm(forms.Form):
    endpoint_url = forms.URLField()

class DeleteForm(forms.Form):
    pass

WSP/rdfedit/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, get_object_or_404, render
from django.template import RequestContext
from django.template.defaulttags import register
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.files import File
from django.core.servers.basehttp import FileWrapper
from django.conf import settings

from dajaxice.core import dajaxice_functions

from WSP.settings import NAMESPACES_DICT, SINDICE_CONFIG_QUERY, SINDICE_CONFIG_MAPPING
from WSP.rdfedit.models import Document, RDF_XML
from WSP.rdfedit.forms import DocumentForm, DeleteForm, EndpointForm
from WSP.rdfedit.spo2rdfjson import spo2rdfjson

from rdflib import Graph, plugin
from rdflib.parser import Parser
from rdflib.serializer import Serializer
from rdflib.namespace import Namespace, NamespaceManager

import os
import cStringIO as StringIO

import json
import sys


reload(sys).setdefaultencoding("utf-8")

"""
Register serializer and parser plugin for correct
interpretation and output of RDFJson and RDF/XML.
"""

plugin.register("rdf-json", Parser,
                "rdflib_rdfjson.rdfjson_parser", "RdfJsonParser")

plugin.register("rdf-json", Serializer,
                "rdflib_rdfjson.rdfjson_serializer", "RdfJsonSerializer")

plugin.register("rdf-json-pretty", Serializer,
                "rdflib_rdfjson.rdfjson_serializer", "PrettyRdfJsonSerializer")


# Create dictionary for namespaces for later bindings and display in the spo-view.
namespaces_dict = NAMESPACES_DICT


def index(request):
    # Handle file upload

    if request.method == 'POST':
        # If upload-button is pressed, upload selected file and display spo-view.
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()
            doc_id = newdoc.id

            # Redirect to the document list after POST
            return spo(request, doc_id)

        endpoint_form = EndpointForm(request.POST)
        if endpoint_form.is_valid():
            endpoint_url = request.POST["endpoint_url"]
            return spo(request, endpoint_url)

    else:
        delete(request)
        form = DocumentForm()  # A empty, unbound form
        endpoint_form = EndpointForm()

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render_to_response(
        'rdfedit/index.html',
        {'documents': documents, 'form': form, 'endpoint_form': endpoint_form},
        context_instance=RequestContext(request)
    )


def delete(request):
    # Delete all files that were uploaded by users.
    del_id_list = [doc.id for doc in Document.objects.all()]
    for del_id in del_id_list:
        del_doc = Document.objects.get(pk=del_id)
        if del_id != 1:
            os.remove(os.path.join(settings.MEDIA_ROOT, del_doc.docfile.name))
            del_doc.delete()
    return HttpResponseRedirect(reverse('WSP.rdfedit.views.index'))


def getrdf(doc_id):
    # Load RDF-graph object by document ID in the Database

    doc = Document.objects.get(pk=doc_id)
    graph = Graph()

    if doc.docfile.name.split(".")[-1] == "ttl":
        graph.load(doc.docfile, format="turtle")

    else:
        graph.load(doc.docfile)

    return graph


def newgraph(request):
    print request.method

    # Create and bind namespaces
    namespace_manager = NamespaceManager(Graph())
    for ns in namespaces_dict:
        namespace_manager.bind(ns, Namespace(namespaces_dict[ns]))

    # Create a new graph
    graph = Graph()
    graph.namespace_manager = namespace_manager

    triple_list = []
    subject_list = []
    predicate_list = []

    subject_set = {}
    predicate_set = {}
    object_set = {}

    # Determine xml:base
    subject_base_test_set = {triple[0] for triple in triple_list}
    base_set = {subject[:subject.rfind("/")] for subject in subject_base_test_set}
    # If all subjects share the same substring-base, this substring-base is likely to be the xml:base.
    if len(base_set) == 1:
        base = str(list(base_set)[0]) + "/"
    else:
        base = ""

    # Serialize graph
    rdfjson = graph.serialize(None, format="rdf-json")

    # 
    triple_fetcher_classes = get_triple_fetcher_classes()

    response = render_to_response('rdfedit/triples.html',
                                  {'rdfjson': rdfjson, 'triple_list': triple_list, 'subject_set': subject_set,
                                   'predicate_set': predicate_set, 'object_set': object_set,
                                   'namespaces_dict': json.dumps(namespaces_dict), 'base': base,
                                   'triple_fetcher_classes': triple_fetcher_classes},
                                  context_instance=RequestContext(request))

    return response


def spo(request, doc_id):
    # Create and bind namespaces
    namespace_manager = NamespaceManager(Graph())
    for ns in namespaces_dict:
        namespace_manager.bind(ns, Namespace(namespaces_dict[ns]), override=False)

    # Load graph from the uploaded file

    if type(doc_id) == int or doc_id == "1":
        # If doc_id is an integer, a file was uploaded. If doc_id is the string "1", the example is parsed.

        graph = getrdf(doc_id)
    else:
        # If doc_id is not an integer, therefore a string, an SPARQL-endpoint url is being parsed
        graph = Graph()
        graph.parse(data=spo2rdfjson(doc_id), format="rdf-json")

        # Generate list of triples
    triple_list = []
    subject_list = []
    predicate_list = []
    object_list = []
    for s, p, o in graph:
        triple_list.append([s, p, o])
        subject_list.append(str(s).encode('utf-8', 'ignore'))
        predicate_list.append(str(p).encode('utf-8', 'ignore'))
        # print str(o).encode('utf-8', 'ignore')
        object_list.append(str(o).decode('utf-8', 'ignore'))

    subject_set = json.dumps(list(set(subject_list)))
    predicate_set = json.dumps(list(set(predicate_list)))
    object_set = json.dumps(list(set(object_list)))


    # Determine xml:base
    subject_base_test_set = {triple[0] for triple in triple_list}
    base_set = {subject[:subject.rfind("/")] for subject in subject_base_test_set}
    # If all subjects share the same substring-base, this substring-base is likely to be the xml:base.
    if len(base_set) == 1:
        base = str(list(base_set)[0]) + "/"
    else:
        base = ""

    # Insert namespaces into graph
    graph.namespace_manager = namespace_manager

    triple_fetcher_classes = get_triple_fetcher_classes()

    # Get the config files
    mapping_config = json.loads(open(SINDICE_CONFIG_MAPPING, 'r').read())
    query_config = json.loads(open(SINDICE_CONFIG_QUERY, 'r').read())
    import_label_lengths = dict()

    for tf_class in triple_fetcher_classes:
        mapping_length = len(mapping_config[tf_class])
        query_length = len(query_config[tf_class])

        if mapping_length >= query_length:
            import_label_lengths[tf_class] = mapping_length
        else:
            import_label_lengths[tf_class] = query_length

    import_config = {"query": query_config, "mapping": mapping_config, "import_label_lengths": import_label_lengths}

    import_config_dj = dict()
    for tf_class in triple_fetcher_classes:
        import_config_dj[tf_class] = dict()





    for tf_class in import_config_dj:
        import_config_dj[tf_class]["query"] = dict()
        import_config_dj[tf_class]["mapping"] = dict()


    for tf_class in import_config["query"]:
        i = 0
        for conf in import_config["query"][tf_class]:
            import_config_dj[tf_class]["query"][i] = {conf : import_config["query"][tf_class][conf]}
            i += 1

    for tf_class in import_config["mapping"]:
        i = 0
        for conf in import_config["mapping"][tf_class]:
            import_config_dj[tf_class]["mapping"][i] = {conf : import_config["mapping"][tf_class][conf]}
            i += 1

    print import_config_dj

    # Serialize graph to RDFJson
    rdfjson = graph.serialize(None, format="rdf-json")
    return render_to_response(
        'rdfedit/triples.html',
        {'rdfjson': rdfjson,
         'triple_list': triple_list,
         'subject_set': subject_set,
         'predicate_set': predicate_set,
         'object_set': object_set,
         'namespaces_dict': json.dumps(namespaces_dict),
         'base': base,
         "triple_fetcher_classes": json.dumps(triple_fetcher_classes),
         "import_config": json.dumps(import_config),
         "import_config_dj": import_config_dj},
        context_instance=RequestContext(request)
    )


def rdf(request, rdfxml_id):
    # Get RDF/XML from the database

    rdfxml_object = RDF_XML.objects.get(pk=rdfxml_id)
    rdfxml_string = rdfxml_object.rdfxml_string


    # Create virtual file and write the RDF/XML string into it
    rdfxml_file = StringIO.StringIO()
    rdfxml_file.write(rdfxml_string.encode('utf-8', 'ignore'))

    # Register response as file download
    response = HttpResponse(rdfxml_file.getvalue(), content_type='application/xml')
    response['Content-Disposition'] = 'attachment; filename="rdf.xml"'

    for doc in RDF_XML.objects.all():
        # Make sure the DB stays clean
        doc.delete()

    return response


def get_triple_fetcher_classes():
    # Get available classes for the triple fetcher
    sindice_query_config = json.loads(open(SINDICE_CONFIG_QUERY, 'r').read())
    triple_fetcher_classes = list()

    for triple_fetcher_class in sindice_query_config:
        triple_fetcher_classes.append(triple_fetcher_class)

    return list(set(triple_fetcher_classes))

WSP/rdfedit/templates/rdfedit/index.html
{% extends "base.html" %}

{% block content %}
	<!-- Row-fluid inside containers for resizable layout -->
	<div class="container">
		<div class="row-fluid heading">
			<div class="span12">
				<h1>WSP Triple Editor</h1>
			</div>
		</div>
		
		<div class="row-fluid subheading">
			<div class="span12">
				<p class="lead">Edit RDF graphs in the browser</p>
			</div>
		</div>

		<form action="{% url "index" %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% load widget_tweaks %}
			<p>{{ form.non_field_errors }}</p>
			<p>
				{{ form.docfile.errors }}
			<div class="control-group">
				<label class="control-label" for="description">
				  <p>{{ form.docfile.label_tag }}</p>
				</label>
				<div class="controls">
				  {{ form.docfile }}
				  <div class="dummyfile">
                    <button class="btn btn-primary"><i class="icon-white icon-upload"></i> Upload</button> 
				    <input id="filename" type="text" class="input disabled" name="filename" readonly>
                    <a id="fileselectbutton" class="btn"><i class="icon-white icon-folder-open"></i> Choose...</a>
				  </div>
				</div>
            </div>
		</form>
        <div>
        <form action="{% url "index" %}" method="post">
            {% csrf_token %}
            <p>Parse from SPARQL Enpoint (e.g. "http://data.linkedmdb.org/sparql")</p>
            <div>
                <button class="btn btn-primary"><i class="icon-white icon-globe"></i> Parse</button>
                {{ endpoint_form.endpoint_url }}
            </div>
        </form>
        </div>
        <div>
            <a href="{% url "spo" 1 %}" class="btn btn-success"><i class="icon-white icon-tag"></i> Example</a>
        </div>
        <div class="new-graph">
			<a href="{% url "newgraph" %}" class="btn btn-info"><i class="icon-white icon-plus-sign"></i> New</a>
		</div>

	</div>
{% endblock %}

WSP/rdfedit/templates/rdfedit/save-index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" contet="width=device-width, initial-scale=1.0">
		<title>WSP Triple Editor</title>
		
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static 'rdfedit/bootstrap/css/bootstrap.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'rdfedit/bootstrap/css/bootstrap-fileupload.css' %}" />
		<link rel="stylesheet" type="text/css" href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css">
		<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic">
		<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,300,400,600,700,800">
	
		<script src="{% static 'rdfedit/jQuery/jquery-2.0.3.min.js' %}"></script>
		<script src="{% static 'rdfedit/bootstrap/js/bootstrap.js' %}"></script>
		<script src="{% static 'rdfedit/bootstrap/js/bootstrap-fileupload.js' %}"></script>
		<script src="{% static 'rdfedit/jQuery/jquery-bootstrap-upload-button.js' %}"></script>
		
			<style type="text/css">
	
	/* Body and heading */
	
	body{
		font-family: 'Open Sans', Helvetica, Arial, sans-serif;
		padding-top: 60px;
	}
	
	.heading, .subheading{
		font-family: 'Ubuntu', Helvetica, Arial, sans-serif;
		text-align: center
	}
	
	p.lead {
		padding-top: 1.5%;
		font-size: 24px;
		line-height: 30px;
	}
	
	p {
		font-size: 18px;
		line-height: 24px;
	}
	
	/* Enable dropdown on hover */
	
	ul.nav li.dropdown:hover ul.dropdown-menu { 
		display: block; 
	}

	/* Style upload button */

	#id_docfile {
	   display: none;
	}
   
	.dummyfile input[type="text"] {
		width: 120px;
		display: inline;
	}

	.filehandler {
		width: 600px;
		float: left;
		padding-top: 4px;
		padding-left: 2px;
	}
	</style>
  </head>
  
  <body>
	<!-- Navigation bar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
		<button type="button" class="btn btn-navbar"
				data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="brand" href="#">WSP Triple Editor</a>
		<div class="nav-collapse collapse">
			<ul class="nav">
				<li class="active"><a href="#">Home</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Tools <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="#">Edit RDF</a></li>
						<li><a href="#">Edit Literals</a></li>
						<li><a href="#">SPARQL</a></li>
					</ul>
				</li>
			</ul>
		</div>
	  </div>
	</div>
	
	<!-- Row-fluid inside containers for resizable layout -->
	<div class="container">
		<div class="row-fluid heading">
			<div class="span12">
				<h1>WSP Triple Editor</h1>
			</div>
		</div>
		
		<div class="row-fluid subheading">
			<div class="span12">
				<p class="lead">Edit RDF graphs in the browser</p>
			</div>
		</div>

		{% if documents %}
			<ul>
			{% for document in documents %}
				<li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
			{% endfor %}
			</ul>
			{% else %}
				<p>No documents uploaded yet.</p>
			{% endif %}
		<form action="{% url "index" %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% load widget_tweaks %}
			<p>{{ form.non_field_errors }}</p>
			<p>
				{{ form.docfile.errors }}
			<div class="control-group">
				<label class="control-label" for="description">
				  <p>{{ form.docfile.label_tag }}{{ form.docfile.help_text }}</p>
				</label>
				<div class="controls">
				  {{ form.docfile }}
				  <div class="dummyfile">
				    <a id="fileselectbutton" class="btn">Choose...</a>
				    <input id="filename" type="text" class="input disabled" name="filename" readonly>
				  </div>
				</div>
			</div>
			</p>
			<p><input type="submit" value="Upload" class="btn btn-primary" /></p>
		</form>
		<form action="{% url "delete" %}" method="post">
			{% csrf_token %}
			<p>Delete all files</p>
			<p><input type="submit" value="Delete" class="btn btn-danger"/></p>
		</form>
	</div>
	
	
  </body>
</html>

WSP/rdfedit/templates/rdfedit/triples.html
{% extends "base.html" %}

{% load url from future %}

{% block content %}


    <div class="triple_table_wrapper">

        <table id="triples" cellpadding="0" cellspacing="0" border="0" class="table table-bordered highlight-row">

            <thead>
            <th>Subject</th>
            <th>Predicate</th>
            <th>Object</th>
            </thead>

            <tbody>
            {% for triple in triple_list %}
                <tr id="row">

                    <!--  <td id="subject" uri="{{ triple.0 }}" contentEditable>{{ triple.0 }}</td> -->

                    <td>

                        <span id="subject" contentEditable>{{ triple.0 }}</span>

                    </td>

                    <td>
                        <span id="predicate" rel="tooltip" title="{{ triple.1 }}">{{ triple.1 }}</span>
                    </td>

                    <td>

                        <span id="object-icon-wrapper"><i id="object-icon" class="icon-white"></i></span>

                        <span id="object" contentEditable>{{ triple.2 }}</span>

                        <span id="delete_triple"><i class="icon-black icon-remove-sign"></i></span>
                    </td>
                </tr>
            {% endfor %}
            </tbody>

            <tfoot>
            <tr>
                <th><input type="text" name="search_subject" value="Search subject" class="search_init"/></th>
                <th><input type="text" name="search_predicate" value="Search predicate" class="search_init"/></th>
                <th><input type="text" name="search_object" value="Search object" class="search_init"/></th>
            </tfoot>
        </table>
    </div>


    <div>
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">

            <!-- Add single triple -->
            <tr id="add_triple">
                <th><input id="add_subject" class="add_init" type="text" value="Add subject"></th>
                <th><input id="add_predicate" class="add_init" type="text" value="Add predicate"/></th>
                <th>
                    <input id="add_object" class="add_init" type="text" value="Add object"/>
                    <button id="add_button" class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> <span>Add triple</span>
                    </button>
                </th>
            </tr>

            <tr id="fetch_triple_set">
                <th><input id="triple_set_keywords" class="add_init" type="text" value="Enter Import Keywords"></th>

                <th> <!-- Add a bootstrap dropdown menu to select the fetcher type -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                id="triple_set_type_select_label">Other
                            <span class="caret"></span>
                        </button>
                        <ul id="triple_set_type_select" class="dropdown-menu">
                            <li><a href="#">Other</a></li>
                        </ul>
                    </div>

                    <input id="triple_set_type_input" class="add_init" type="text" value="Choose Type">
                </th>
                <th>
                    <div class="btn-group">
                        <button id="fetch_triple_set_button" class="btn btn-info"><i class="icon-white icon-repeat"></i>
                            Fetch graphs
                        </button>

                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                id="graph_selector_label">
                            Choose Graph
                            <span class="caret"></span>
                        </button>
                        <ul id="graph_selector" class="dropdown-menu">
                        </ul>
                    </div>
                </th>
            </tr>
        </table>
    </div>

    <button id="rdf_export_button" class="btn btn-primary"><i class="icon-white icon-download"></i> Download as RDF/XML
    </button>
    <button id="undo_button" class="btn btn-primary"><i class="icon-white icon-undo"></i> Undo</button>
{% endblock %}

{% block templatescripts %}

    <script>
        /* Load RDFJSON from Django */
        rdfjson = JSON.parse('{{ rdfjson|escapejs }}');
        namespaces_dict = JSON.parse('{{ namespaces_dict|escapejs }}');
        base = '{{ base }}'
        subject_set = JSON.parse('{{ subject_set|escapejs }}');
        predicate_set = JSON.parse('{{ predicate_set|escapejs }}');
        generic_rdfURL = '{% url "rdf" 999999 %}';
        object_set = JSON.parse('{{ object_set|escapejs }}');
        triple_fetcher_classes = JSON.parse('{{ triple_fetcher_classes | escapejs }}');
        import_config = JSON.parse('{{ import_config | escapejs }}');

    </script>

    {% load staticfiles %}
    <script src="{% static 'rdfedit/jQuery/jquery.dataTables.js' %}"></script>
    <script src="{% static 'rdfedit/jQuery/dataTables.fnDisplayRow.js' %}"></script>
    <script src="{% static 'rdfedit/jQuery/rdfedit-triples.js' %}"></script>
    <script src="{% static 'rdfedit/jQuery/DT_bootstrap.js' %}"></script>
    <script src="{% static 'rdfedit/jQuery/spin.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'rdfedit/bootstrap/css/DT_bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'rdfedit/css/rdfedit-triples.css' %}"/>
{% endblock %}

{% block dropdown-tools %}

    <li id="dropdown_undo"><a><i class="icon-black icon-undo"></i> Undo</a></li>
    <li id="dropdown_rdf_export"><a><i class="icon black icon-download"></i> Download as RDF/XML</a></li>
    <li id="dropdown_import-config"><a><i class="icon black icon-wrench"></i> Import/Mapping Configuration</a></li>

{% endblock %}

{% block templatestyles %}

{% endblock %}